In [3]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

Original code to print the output prediction

In [4]:
while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

[[5.2060891e-04 9.9850488e-01 2.7712696e-07 9.7423798e-04]]
[[6.4063976e-03 8.6232340e-01 8.1779966e-05 1.3118848e-01]]
[[1.9512275e-03 9.9408698e-01 9.2927837e-07 3.9609037e-03]]
[[3.1251961e-03 9.9579251e-01 9.6948713e-07 1.0813075e-03]]
[[1.7573524e-03 9.9655980e-01 4.8443491e-07 1.6822568e-03]]
[[2.3553378e-04 9.9829203e-01 5.4074894e-07 1.4718785e-03]]
[[2.4233023e-03 9.9626899e-01 2.2319887e-06 1.3054316e-03]]
[[4.1307099e-03 9.9207121e-01 3.3147467e-06 3.7947246e-03]]
[[2.6145184e-03 9.9573612e-01 7.4034784e-07 1.6486904e-03]]
[[6.8147318e-04 9.9917573e-01 3.8818612e-08 1.4268796e-04]]
[[3.0564965e-04 9.9955469e-01 2.0970122e-08 1.3970326e-04]]
[[1.16563395e-04 9.99609292e-01 9.70852554e-08 2.74093472e-04]]
[[3.1430859e-04 9.9892163e-01 2.0284122e-07 7.6392613e-04]]
[[1.18694385e-04 9.99601424e-01 4.30513296e-08 2.79957720e-04]]
[[5.5216922e-04 9.9805021e-01 3.1814955e-07 1.3972792e-03]]
[[1.7650137e-03 9.9626464e-01 1.1977415e-06 1.9690618e-03]]
[[5.6107673e-03 9.9194497e-01 8.

Testing to produce an output value from the above script

In [5]:
def get_prediction():

    model = load_model('keras_model.h5')
    cap = cv2.VideoCapture(0)
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

    output = []
    
    while True:
        ret, frame = cap.read()
        resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
        image_np = np.array(resized_frame)
        normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
        data[0] = normalized_image
        prediction = model.predict(data)
        cv2.imshow('frame', frame)
        # Press q to close the window
        output = prediction
        break
    return output

In [6]:
get_prediction()

error: OpenCV(4.5.5) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
